### ISSUE TITLE
Module seems to have issues with Nuxt 3.9.0

### ISSUE THREAD

**Issue by okeke-ugochukwu** [OyewoleOyedeji/nuxt-phosphor-icons#7]
@OyewoleOyedeji 
Hi. I just updated a project I'm working on from ```Nuxt 3.7.4``` to the just released ```3.9.0```, using ```nuxi upgrade --force```
On starting the server I get an error:

```
Cannot start nuxt:  Nuxt module should be a function: nuxt-phosphor-icons
```

I init a new project, clean install, installed just the module and tried again. 
Error message persists. 

I can't find much information on the error

**Comment by oyedejioyewole** [comment]
Have you tried using the latest version?

**Comment by oyedejioyewole** [comment]
> Have you tried using the latest version?

If it still doesn't work provide a minimal reproduction of your project on CodeSandbox

**Comment by okeke-ugochukwu** [comment]
Last release says ```v1.1.0``` same as the new project

**Comment by oyedejioyewole** [comment]
> Last release says `v1.1.0` same as the new project

brb

**Comment by oyedejioyewole** [comment]
Could you provide the error log?

**Comment by okeke-ugochukwu** [comment]
![Screenshot (77)](https://github.com/OyewoleOyedeji/nuxt-phosphor-icons/assets/40551812/02d1e184-7317-4534-ace1-d8ffcdef11d5)

**Comment by okeke-ugochukwu** [comment]
Not quite fixed yet

![Screenshot (78)](https://github.com/OyewoleOyedeji/nuxt-phosphor-icons/assets/40551812/14843e38-4f98-45be-b396-a3add7796095)

**Comment by oyedejioyewole** [comment]
@okeke-ugochukwu I've found the problem now, and it should hopefully be fixed with version 1.1.5. Sorry for any inconvenience

**Comment by oyedejioyewole** [comment]
The module now works perfectly with Nuxt 3.9.0 after running tests on different environments. Thanks for raising the alarm 😄

**Comment by okeke-ugochukwu** [comment]
Yeah it works now. Thank you! 🙌
